name: Build and Release Wallify

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'
        
    - name: Make build script executable
      run: chmod +x build_installer.sh
      
    - name: Build Wallify
      run: ./build_installer.sh
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wallify-build
        path: build/
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/Wallify.zip
          build/Wallify-Installer.dmg
          build/Wallify.pkg
        body_path: build/GITHUB-RELEASE.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 